tasks:
- name: Install Elixir and Livebook
  before: |
    wget https://packages.erlang-solutions.com/erlang-solutions_2.0_all.deb && sudo DEBIAN_FRONTEND=noninteractive dpkg -i erlang-solutions_2.0_all.deb
    sudo DEBIAN_FRONTEND=noninteractive apt-get update && sudo DEBIAN_FRONTEND=noninteractive apt-get install -y esl-erlang elixir
    mix local.hex --force
    mix local.rebar --force
    mix escript.install hex livebook --force
  command: |
    export PATH=$HOME/.mix/escripts:$PATH
    livebook server
  openMode: tab-after

ports:
- port: 8080
  onOpen: notify

vscode:
  extensions:
    - dracula-theme.theme-dracula
    - elixir-lsp.elixir-ls
    - matklad.rust-analyzer
